<script src="/bootstrap.bundle.min.js"></script>
<script src="/popper.min.js"></script>
<style>
   body {
      background-color: #f3f4f6 !important;
   }
</style>
<link href="/bootstrap.min.css" rel="stylesheet">
   <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
      <div class="container-fluid">
         <a class="navbar-brand" href="#">Singleton</a>
         <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
               <li class="nav-item">
                  <a class="nav-link" href="/tickets">Tickets</a>
               </li>
            </ul>
         </div>
      </div>
   </nav>