<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8" />
        <title>Tickets</title>
    </head>
    <body>
        <div style="display: flex; flex-direction: row;">
            <table>
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Descripción</th>
                        <th>Dueño</th>
                        <th>Encargado</th>
                        <th>Estado</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($data as $entry): ?>
                        <tr>
                            <td><?php echo $entry["id"]?></td>
                            <td><?php echo $entry["description"]?></td>
                            <td><?php echo $entry["s_name"] . " " . $entry["s_lastname"]?></td>
                            <td><?php echo $entry["a_name"] . " " . $entry["a_lastname"]?></td>
                            <td><?php echo $entry["status"]?></td>
                            <td>
                                <?php if ($_SESSION["user_id"] == $entry["student_id"]):?>
                                    <?php if ($entry["status"] !== "RETURNED"): ?>
                                        <?php if ($entry["status"] !== "CLOSED"): ?>
                                            <a href="/tickets/delete/<?php echo $entry["id"] ?>">
                                                <button>Eliminar</button>
                                            </a>
                                        <?php endif ?>
                                    <?php else: ?>
                                    <form action="/tickets/update/<?php echo $entry["id"] ?>" method="POST">
                                        <input name="status" value="CLOSED" hidden>
                                        <input name="description" value="<?php echo $entry["description"] ?>" hidden>
                                        <button>Confirmar</button>
                                    </form>
                                    <?php endif ?>
                                <?php endif ?>
                                <?php if ($_SESSION["user_id"] == $entry["admin_id"] && $entry["status"] !== "CLOSED"):?>
                                    <form action="/tickets/update/<?php echo $entry["id"] ?>" method="POST">
                                        <input name="description" value="<?php echo $entry["description"] ?>" hidden>
                                        <select name="status">
                                            <option selected value="PENDING">Pendiente</option>
                                            <option value="SEARCHING">Buscando</option>
                                            <option value="FOUND">Encontrado</option>
                                            <option value="RETURNED">Devuelto</option>
                                            <option value="LOST">Perdido</option>
                                        </select>
                                        <button>Actualizar</button>
                                    </form>
                                    </a>
                                <?php endif ?>
                            </td>
                            <
                        </tr>
                    <?php endforeach?>
                </tbody>
            </table>
            <?php if ($_SESSION["user_role"] == "S"):?>
                <div>
                    <h2>Registra un objeto</h2>
                    <form action="/tickets/create" method="POST">
                        <label>Descripcion</label>
                        <input name="description" minlength="1">
                        <input name="status" value="PENDING" hidden>
                        <input name="location_id" value="3" hidden>
                        <button>Enviar</button>
                    </form>
                </div>
            <?php endif; ?>
        </div>
    </body>
</html>